name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build & Test (no config cache, no daemon)
        run: |
          ./gradlew --version
          ./gradlew clean test installDist --no-daemon --no-configuration-cache

      # Optional: publish the zip so you can download the app from the Actions page
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: arkanoid-dist
          path: build/distributions/*.zip
