name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 👇 THIS is the "make gradlew executable" block
      - name: Make gradlew executable (Linux)
        run: chmod +x gradlew

      - name: Build & test
        run: ./gradlew --no-daemon clean test installDist
